/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotauthAuthRegisterRouteImport } from './routes/_notauth/auth/register'
import { Route as NotauthAuthLoginRouteImport } from './routes/_notauth/auth/login'
import { Route as NotauthAuthForgotPasswordRouteImport } from './routes/_notauth/auth/forgot-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotauthAuthRegisterRoute = NotauthAuthRegisterRouteImport.update({
  id: '/_notauth/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotauthAuthLoginRoute = NotauthAuthLoginRouteImport.update({
  id: '/_notauth/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotauthAuthForgotPasswordRoute =
  NotauthAuthForgotPasswordRouteImport.update({
    id: '/_notauth/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/auth/login': typeof NotauthAuthLoginRoute
  '/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/auth/login': typeof NotauthAuthLoginRoute
  '/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_notauth/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/_notauth/auth/login': typeof NotauthAuthLoginRoute
  '/_notauth/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/forgot-password' | '/auth/login' | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/forgot-password' | '/auth/login' | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/_notauth/auth/forgot-password'
    | '/_notauth/auth/login'
    | '/_notauth/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotauthAuthForgotPasswordRoute: typeof NotauthAuthForgotPasswordRoute
  NotauthAuthLoginRoute: typeof NotauthAuthLoginRoute
  NotauthAuthRegisterRoute: typeof NotauthAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notauth/auth/register': {
      id: '/_notauth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof NotauthAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notauth/auth/login': {
      id: '/_notauth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof NotauthAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notauth/auth/forgot-password': {
      id: '/_notauth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof NotauthAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotauthAuthForgotPasswordRoute: NotauthAuthForgotPasswordRoute,
  NotauthAuthLoginRoute: NotauthAuthLoginRoute,
  NotauthAuthRegisterRoute: NotauthAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
